### ISSUE TITLE
Support parallel builds

### ISSUE THREAD

**Issue by jakub-bochenski** [jcgay/maven-profiler#8]
Seeing this doesn't support multi-module builds I don't think -T is supported 

See also https://github.com/takari/maven-profiler/issues/6

**Comment by jcgay** [comment]
When you say "this doesn't support multi-module" do you refer to #9 ?
Because it does in fact (even if as you have discovered, the report is always written in the root project)

This extension should also work in parallel, do you have any error to share or timing report that do not seems right when run in parallel ?

Thx !

**Comment by jakub-bochenski** [comment]
Well the original title was "Document if this extension supports parallel build". So if it does -- that's great, would you mind giving a clear statement in the docs?

**Comment by jcgay** [comment]
Sure I can add it 👍
